import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '../models/movie_model.dart';
import '../models/movie_search_response.dart';

part 'movie_remote_data_source.g.dart';

/// TMDB endpoints used by the app. The implementation is generated by
/// `retrofit_generator`; the `api_key` query parameter is injected globally by
/// `ApiKeyInterceptor`.
@RestApi()
abstract class MovieRemoteDataSource {
  factory MovieRemoteDataSource(Dio dio, {String? baseUrl}) =
      _MovieRemoteDataSource;

  @GET('/search/movie')
  Future<MovieSearchResponse> searchMovies(
    @Query('query') String query, {
    @Query('page') int page = 1,
    @Query('include_adult') bool includeAdult = false,
  });

  @GET('/movie/{id}')
  Future<MovieModel> getMovieDetails(@Path('id') int id);
}
